# yaml-language-server: $schema=./.appwrite/appwriteUtilsConfigSchema.json
appwriteEndpoint: 'https://cloud.appwite.io/v1' # Your Appwrite endpoint
appwriteProject: 'YOUR_PROJECT_ID' # Your Appwrite project
appwriteKey: 'YOUR_API_KEY' # Your Appwrite API key (needs storage and databases at minimum)
appwriteClient: null # Your Appwrite client -- don't worry about this
enableDevDatabase: true # Enable development database alongside main
enableBackups: true # Enable backups
backupInterval: 3600 # Backup interval in seconds
backupRetention: 30 # Backup retention in days
enableBackupCleanup: true # Enable backup cleanup
enableMockData: false # Enable mock data generation
enableWipeOtherDatabases: true # Enable wiping other databases
documentBucketId: 'documents' # Your Appwrite bucket ID for documents
databases:
  - $id: 'main'
    name: 'Main'
  - $id: 'staging'
    name: 'Staging'
  - $id: 'dev'
    name: 'Development'
collections:
  - name: 'Members'
    $permissions:
      - permission: read
        target: any
      - permission: create
        target: users
      - permission: update
        target: users
      - permission: delete
        target: users
    attributes:
      - key: 'name'
        type: 'string'
        size: 255
        required: true
      - key: 'email'
        type: 'string'
        size: 255
        required: false
      - key: 'idOrig'
        type: 'string'
        size: 255
        required: false
      - key: 'dogs'
        type: 'relationship'
        relatedCollection: 'Dogs'
        relationType: 'oneToMany'
        twoWay: true
        twoWayKey: 'owner'
        side: 'parent'
        onDelete: 'cascade'
        importMapping: { originalIdField: 'idOrig', targetField: 'ownerIdOrig' }
      - key: 'dogIds'
        type: 'string'
        size: 255
        array: true
      - key: 'profilePhoto'
        type: 'string'
        size: 255
        required: false
      - key: 'profilePhotoTest'
        type: 'string'
        size: 255
        required: false
    indexes:
      - key: 'name_index'
        type: 'key'
        attributes: ['name']
    importDefs:
      - filePath: 'importData/members.json'
        basePath: 'RECORDS'
        attributeMappings:
          - oldKey: 'id'
            targetKey: 'idOrig'
            converters: ['anyToString']
            postImportActions:
              - action: 'checkAndUpdateFieldInDocument'
                params:
                  - "{dbId}"
                  - "{collId}"
                  - "{docId}"
                  - "idOrig"
                  - "{id}"
                  - "{$id}"
          - oldKey: 'name'
            targetKey: 'name'
          - oldKey: 'email'
            targetKey: 'email'
          - oldKey: 'doesntMatter'
            targetKey: 'profilePhoto'
            fileData: { name: "profilePhoto_{id}", path: "importData/profilePhotos" }
          - oldKey: 'photoUrl'
            targetKey: 'profilePhotoTest'
            fileData: { name: "profilePhotoTest_{id}", path: "{photoUrl}" }
  - name: 'Dogs'
    $permissions:
      - permission: read
        target: any
      - permission: create
        target: users
      - permission: update
        target: users
      - permission: delete
        target: users
    attributes:
      - key: 'name'
        type: 'string'
        size: 255
        required: true
      - key: 'breed'
        type: 'string'
        size: 255
        required: false
      - key: 'age'
        type: 'integer'
        required: false
        min: 0
        max: 100
      - key: 'idOrig'
        type: 'string'
        size: 20
        required: false
      - key: 'ownerIdOrig'
        type: 'string'
        size: 255
        required: false
      - key: 'vetRecords'
        type: 'string'
        size: 255
        required: false
      - key: 'vetRecordIds'
        type: 'string'
        size: 255
        array: true
        required: false
    indexes:
      - key: 'ownerIdIndex'
        type: 'key'
        attributes: ['ownerIdOrig']
    importDefs:
      - filePath: 'importData/dogs.json'
        basePath: 'RECORDS'
        attributeMappings:
          - oldKey: 'id'
            targetKey: 'idOrig'
          - oldKey: 'name'
            targetKey: 'name'
          - oldKey: 'breed'
            targetKey: 'breed'
          - oldKey: 'age'
            targetKey: 'age'
          - oldKey: 'ownerId'
            targetKey: 'ownerIdOrig'
          - oldKey: 'vetRecords'
            targetKey: 'vetRecords'
            converters: ['stringifyObject']
          - oldKey: 'vetRecords.[any].id'
            targetKey: 'vetRecordIds'
            converters: ['anyToStringArray[arr]']
      - filePath: 'importData/dogs.json'
        basePath: 'RECORDS'
        type: 'update'
        updateMapping: { originalIdField: 'id', targetField: 'idOrig' }
        attributeMappings:
          - oldKey: 'name'
            targetKey: 'name'
          - oldKey: 'breed'
            targetKey: 'breed'
          - oldKey: 'age'
            targetKey: 'age'