# yaml-language-server: $schema=./.appwrite/appwriteUtilsConfigSchema.json
appwriteEndpoint: 'https://cloud.appwrite.io/v1' # Your Appwrite endpoint
appwriteProject: 'YOUR_PROJECT_ID' # Your Appwrite project
appwriteKey: 'YOUR_API_KEY' # Your Appwrite API key (needs storage and databases at minimum)
appwriteClient: null # Your Appwrite client -- don't worry about this
enableDevDatabase: true # Enable development database alongside main
enableBackups: true # Enable backups
backupInterval: 3600 # Backup interval in seconds
backupRetention: 30 # Backup retention in days
enableBackupCleanup: true # Enable backup cleanup
enableLocalImport: false # Enable local import
enableMockData: false # Enable mock data generation
enableWipeOtherDatabases: true # Enable wiping other databases
databases:
  - $id: 'main'
    name: 'Main'
  - $id: 'staging'
    name: 'Staging'
  - $id: 'dev'
    name: 'Development'
collections:
  - name: 'Members'
    $permissions:
      - permission: read
        target: any
      - permission: create
        target: users
      - permission: update
        target: users
      - permission: delete
        target: users
    attributes:
      - key: 'name'
        type: 'string'
        size: 255
        required: true
      - key: 'email'
        type: 'string'
        size: 255
        required: false
      - key: 'idOrig'
        type: 'string'
        size: 255
        required: false
      - key: 'dogs'
        type: 'relationship'
        relatedCollection: 'Dogs'
        relationType: 'oneToMany'
        twoWay: true
        twoWayKey: 'owner'
        side: 'parent'
        onDelete: 'cascade'
        importMapping: { originalIdField: 'idOrig', targetField: 'ownerIdOrig' }
      - key: 'dogIds'
        type: 'string'
        size: 255
        array: true
    indexes:
      - key: 'name_index'
        type: 'key'
        attributes: ['name']
    importDefs:
      - filePath: 'importData/members.json'
        basePath: 'RECORDS'
        attributeMappings:
          - oldKey: 'id'
            targetKey: 'idOrig'
            converters: ['anyToString']
            postImportActions:
              - action: 'updateCreatedDoc'
                params:
                  - "{dbId}"
                  - "{collectionId}"
                  - "{createdDocId}"
                  - { key: "ownerIdOrig", value: "{createdDocId}"}
          - oldKey: 'name'
            targetKey: 'name'
          - oldKey: 'email'
            targetKey: 'email'
  - name: 'Dogs'
    $permissions:
      - permission: read
        target: any
      - permission: create
        target: users
      - permission: update
        target: users
      - permission: delete
        target: users
    attributes:
      - key: 'name'
        type: 'string'
        size: 255
        required: true
      - key: 'breed'
        type: 'string'
        size: 255
        required: false
      - key: 'age'
        type: 'integer'
        required: false
        min: 0
        max: 100
      - key: 'ownerIdOrig'
        type: 'string'
        size: 255
        required: false
      # - key: 'owner'
      #   type: 'relationship'
      #   relatedCollection: 'Members'
      #   relationType: 'manyToOne'
      #   twoWay: true
      #   twoWayKey: 'dogs'
      #   side: 'child'
      #   onDelete: 'cascade'
    indexes:
      - key: 'ownerIdIndex'
        type: 'key'
        attributes: ['ownerIdOrig']
    importDefs:
      - filePath: 'importData/dogs.json'
        basePath: 'RECORDS'
        attributeMappings:
          - oldKey: 'id'
            targetKey: '$id'
          - oldKey: 'name'
            targetKey: 'name'
          - oldKey: 'breed'
            targetKey: 'breed'
          - oldKey: 'age'
            targetKey: 'age'
          - oldKey: 'ownerId'
            targetKey: 'ownerIdOrig'